# This is a basic workflow to help you get started with Actions

name: DEPLOYING

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
  
jobs:
  run_python:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Set Environment Variables
        uses: ./.github/actions/setvars
        with:
          varFilePath: ./.github/variables/myvars.env
      - name: Set up python environment
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: MAIN BRANCH CLUSTER
        if: github.ref == 'refs/heads/main'
        env:
          CLUSTER_ID: '1234'
      - name: NOW RUN PYTHON
        run: |
          python script.py
        
