# This is a basic workflow to help you get started with Actions

name: workflow

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    if: ${{ github.ref == 'refs/heads/main' }}
   
    runs-on: ubuntu-latest
    steps:
      - name: Set Environment Variables
        uses: ./.github/actions/setvars
        with:
          varFilePath: ./.github/variables/myvars.env
